/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.basics;
import org.jetbrains.annotations.NotNull;

import java.util.Random;


public class App {

    public static void main(String[] args) {
        int[] array = roll(6);
        String arrays[] = {"sum", "san", "nad", "sta"};
        boolean num = containsDuplicates(arrays);
        System.out.println(num);
    }

    public static int[] roll(int n) {
        int[] arr = new int[6];
        Random rand = new Random(6);
        int result;
        for (int i = 0; i < n; i++) {
            result = rand.nextInt(n);
            result++;
            arr[i] = result;
            System.out.println(arr[i]);
        }
        return arr;

    }

    public static boolean containsDuplicates(String arrayss[]) {
        for (int i = 0; i < arrayss.length; i++) {
            for (int j = i + 1; j < arrayss.length; j++) {
                if (arrayss[i] == arrayss[j]) {
                    System.out.println("False");

                }
            }
        }
        return false;
    }

}
